batch_size = 16
First training for Resnet
1~7: args_Res = {
    'num_of_generate_data_for_train': 1024,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}

8~20: args_Res = {
    'num_of_generate_data_for_train': 512,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}

拉高epoch看會不會繼續收斂
21~23 : args_Res = {
    'num_of_generate_data_for_train': 1200,
    'epochs': 128,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}

將epoch改回比原樣低(32)，因為大概40後就沒有過多下降趨勢，把greedy關掉，試著修改他產生自己畫圈的笨行為
24~33 : args_Res = {
    'num_of_generate_data_for_train': 1200,
    'epochs': 32,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}

結果原本模型已經過於fit貪婪的方式了，繼續拉高盤面與epoch試著調整回來
34~35 : args_Res = {
    'num_of_generate_data_for_train': 1500,
    'epochs': 128,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}
訓練結果: 依照loss來看慘不忍睹，前期不會下讓步棋，不過到最後還是不會得分，導致把自己逼入絕境

從新的模型頭開始練
36 : args_Res = {
    'num_of_generate_data_for_train': 1500,
    'epochs': 128,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}


37~45 : args_Res = {
    'num_of_generate_data_for_train': 1024,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}
結果: 以loss來看完全沒有改善，猜測是因為隨機性取太高(取4)



加強greedyAlg，使其不下送分步，把訓練時的隨機取predict取消，一律選最高機率，從新的模型頭開始練
46~47 : args_Res = {
    'num_of_generate_data_for_train': 1024,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}

練了47個模型後發現：因程式碼錯誤，導致模型的訓練資料採用的是model的predict，但實際上卻不是。
從新的模型頭開始練

batch_size = (2*m-1)*(2*n-1)
48~49 : args_Res = {
    'num_of_generate_data_for_train': 1500,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}


batch_size = 16，上一次訓練完起伏稍大但loss還是有下降
50~53 : args_Res = {
    'num_of_generate_data_for_train': 800,
    'epochs': 64,
    'batch_size': batch_size,
    'verbose': True,
    'type': 0,
    'train': True,
    'load_model_name': None
}